name: GitHub Action for pylint
on: [push]
jobs:
  build:
  
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        platform: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: cclauss/GitHub-Action-for-pylint@0.7.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Analyse code with pylint   
        run: pylint **/*.py
      
